### PR TITLE
Some stuff to handle creation of new run plans / config files

### PR DESCRIPTION
**Pull request by EdLeming**

### CODE REVIEW

**Comment by EdLeming** [comment]
@jlidgard  @jackdunger. I've put this request in there since I know Jeff's been doing some dev. We should decide on who is the keeper of the "master" repo that we all pull into

**Comment by EdLeming** [comment]
Oh shit. Looks like I added all my venv with some catch all commit at the start. I'll tidy tomorrow.

**Comment by jlidgard** [comment]
I'm going to push my repo to snoplus/smellie unless @jackdunger has any concerns. Then submit the PR there. its time we cleaned up the old repo.

**Comment by jackdunger** [comment]
@jlidgard what do you plan to do? If you mean deleting everything in the old repository and adding all of the files in here in one go that sounds like a bad idea. You would loose all the history etc. 

@EdLeming, completely agree. The plan had been to merge things into the repository currently under my name and then just give it to snoplus, with a bunch of administrators. But we ended up one giant pull request with everything going in there and waiting to be able to review/merge that. 

Wherever it lives, I feel strongly that it's important that all changes have someone other than the author look through them. Otherwise we are back to where we started with the old repository.

**Comment by jlidgard** [comment]
Ideally I'd like to overwrite the old with the new keeping the history.
The code on my branch reflects whats running on snodrop. I think push it all, review it piece at a time and begin making PR's + I can start making new PR's for new features.

**Comment by jackdunger** [comment]
Hi @jlidgard. A couple of questions:
On the first point, is that possible? They are separate repositories without a shared history, would be interested to hear. 

On the second - push it all to where?

**Comment by jlidgard** [comment]
I'm unsure. I've been looking. This post 
http://stackoverflow.com/questions/33088588/replace-one-project-with-another-on-git-repository
changes the remote and force pushes.

I think push it to snoplus/smellie. What's there is years old/outdated/doesn't work. If we just overwrite + remove old files with one big push, the history is saved in the commit history right? Then we can begin creating new, incremental PR's.
If you want to push it first to your's, then to snoplus, that would be fine too, but it would be nice to have working code on snoplus/smellie

**Comment by EdLeming** [comment]
I think the best way would be to archive the current snoplus/smellie repo somewhere sensible (and backed up!), then simply overwrite. The /data/snoplus directory would be ideal, but it's not backed up. Perhaps we could get in contact with sys-admin to see what they suggest. 

Seeing as this code is now defunkt, and it's use would result in SMELLIE being in an undefined state, we should consider it's availability on the snoplus repo as actively dangerous. It should definitely be moved somewhere else so there is no potential for a version from before the first 'newSmellie'  commit to be checked out by mistake.

**Comment by jackdunger** [comment]
Looks like that should do the same thing, nice 👍 

But, let's not push everything over there from this branch. If we just use the github repository to store what ever happens to be on SNODROP at any given moment it's just a back up and we already have  those. We started this repository to get away from the 'it works' way of doing things. 

Krish and I had ensured that everything in the main trunk of this repo had been double checked, made sense to someone other than the author, had documentation and wasn't full of commented code. We should continue to do that between us and @EdLeming , only merging bits of code once you are (at least temporarily) finished with them.

I agree we're stuck at the moment because the repository now lags behind what we'll use, but the right way to fix that is to guarantee the quality of the new stuff up rather than using the repository to mirror the machine.

**Comment by jackdunger** [comment]
Just seen @EdLeming's comment - I agree. Presumably we can ask smellie to be transferred to one of you guys from snoplus? Or import it to an Oxford SNOPLUS gitlab with a shared password

**Comment by EdLeming** [comment]
I just created a oxford-snoplus group on gitlab. @jlidgard could you sign up for an account and I'll add you.

https://gitlab.com/oxford-snoplus

**Comment by jlidgard** [comment]
how about https://gitlab.physics.ox.ac.uk ?

**Comment by jlidgard** [comment]
I'm an admin of snoplus/smellie, I think you are too Jack?

**Comment by jackdunger** [comment]
I got the invite, thanks. @EdLeming are you just adding the `database_file_builder` package in this one? If so, I'd suggest you could submit it to the main PR, Jeff or I can look through it briefly, merge and then Jeff can pull it back in here.

**Comment by jackdunger** [comment]
Yes I think so

**Comment by jlidgard** [comment]
The department owns + maintains gitlab.physics.ox.ac.uk, I think this is safer?

**Comment by EdLeming** [comment]
OK. As per @jlidgard's suggestion I've create a group on the oxford server:

https://gitlab.physics.ox.ac.uk/snoplus

It looks like neither of you are users on this server yet. Please create an account (you just need to sign in with your oxford credentials @ gitlab.physics.ox.ac.uk) and I'll add you both to the group. We can then archive the current snoplus/smellie on that server. 

Back to @jackdunger, yes, I'm just adding database_file_builder. It looks like the main PR is from jlidgard:master to jackdunger:master. I'll put in a new request to jlidgard:master now with just the database_file_builder.

**Comment by jlidgard** [comment]
I'm all for backing up the old stuff and archiving.
I know you and Krish went over the initial commit to clean it up, but that code was still riddled with bugs, even after it was reviewed. I'd like to replace the repo now with working, tested code. We can then start the review process again, make PR's for style etc.

**Comment by jlidgard** [comment]
I've signed up. Is there a clever way to archive it (history included) or just zip it?

**Comment by jackdunger** [comment]
Just working isn't enough - again, that's what we had before. 

The PR was waiting to reach a reasonable standard before review, and now we've just waited until that's considered too much effort and merged it anyway.

The existing code is riddled with bugs because the fixes when they were found, they have been sitting somewhere in this branch for months buried with lots of new features.  

I appreciate that mine is just one opinion on this, but I strongly disagree with this way of doing it. reviewing after a merge will never work

**Comment by jackdunger** [comment]
on the gitlab you should be able to transfer the repository including the commit history. Look up github->gitlab migration

**Comment by jlidgard** [comment]
I'd really like it to be clean + nice style + reviewed too. I think my branch is OK. I believe I've kept it organised and in the same style. I'll admit there are a few things lacking (function documentation). I'll go on a cleanup effort.
If you see anything terribly wrong with it, let me know and I can fix it..

**Comment by EdLeming** [comment]
@jlidgard no! Don't merge this mess. It's been tidied and pulled into Jack's branch separately.

**Pull request merged**
